package com.wzl.crm.settings.mapper;

import com.wzl.crm.settings.domain.DicValue;

import java.util.List;
import java.util.Map;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Apr 19 19:21:16 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Apr 19 19:21:16 CST 2023
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Apr 19 19:21:16 CST 2023
     */
    int insertSelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Apr 19 19:21:16 CST 2023
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Apr 19 19:21:16 CST 2023
     */
    int updateByPrimaryKeySelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Apr 19 19:21:16 CST 2023
     */
    int updateByPrimaryKey(DicValue record);

    /**
     * 根据type-code查询字典
     */
    List<DicValue> selectDicValueByTypeCode(String typeCode);

    /**
     * 根据id查询所在的OrderNo
     */
    int selectDicToOrderNo(Map<String,Object> map);
}